import React from "react";
import {
  ApplicationProvider,
  Layout,
  Button,
  IconRegistry
} from "@ui-kitten/components";
import { EvaIconsPack } from "@ui-kitten/eva-icons";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { mapping, dark as darkTheme } from "@eva-design/eva";
import { default as appTheme } from "./custom-theme.json"; // <-- Import custom app theme generated by EVA Design Tool
import { AppNavigator } from "./navigation.component";

const theme = { ...darkTheme, ...appTheme };

const App = () => (
  <React.Fragment>
    <IconRegistry icons={EvaIconsPack} />
    <ApplicationProvider mapping={mapping} theme={theme}>
      <SafeAreaProvider>
        <AppNavigator />
      </SafeAreaProvider>
    </ApplicationProvider>
  </React.Fragment>
);

export default App;
